name: gutendex_app
description: A book listing app using the Gutendex API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management (Cubit)
  flutter_bloc: ^8.1.3
  
  # Networking & API Interaction
  dio: ^5.4.0
  
  # Data Caching & Models for Bonus Feature
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  
  # Service Locator / Dependency Injection (for Clean Architecture)
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # UI & Utilities
  cached_network_image: ^3.3.1 # For book cover images
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2 # For offline mode

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation tools for code quality
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true